import type { ExecutiveHealthSnapshot } from "./executive-health.js";

function esc(value: unknown): string {
  return String(value ?? "—").replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[char] ?? char);
}

function label(status: ExecutiveHealthSnapshot["status"]): string {
  if (status === "ready") return "READY";
  if (status === "watch") return "WATCH";
  if (status === "blocked") return "BLOCKED";
  if (status === "recovery_required") return "RECOVERY REQUIRED";
  return "UNKNOWN";
}

export function renderExecutiveDashboard(health: ExecutiveHealthSnapshot, meta: { release: string; mode: string }): string {
  const statusClass = health.status === "ready" ? "ok" : health.status === "watch" ? "warn" : health.status === "unknown" ? "neutral" : "danger";
  const blockers = health.blockers.length ? health.blockers.map((item) => `<li>${esc(item)}</li>`).join("") : "<li>none</li>";
  const warnings = health.warnings.length ? health.warnings.map((item) => `<li>${esc(item)}</li>`).join("") : "<li>none</li>";
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="30"><title>HENUVOKODAN — Executive Health</title><style>
:root{font-family:Inter,system-ui,sans-serif;color:#e8e4da;background:#10110f}*{box-sizing:border-box}body{margin:0;background:#10110f}main{width:min(1380px,calc(100% - 32px));margin:auto;padding:28px 0 60px}a{color:#d5c397;text-decoration:none}.top{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:18px}.eyebrow{letter-spacing:.18em;font-size:11px;color:#aaa28f}h1{margin:4px 0 0;font-size:28px}.meta{text-align:right;font-size:12px;color:#8d887c}.hero,.card,.panel{border:1px solid #34362f;background:#171915;border-radius:8px}.hero{padding:22px;border-left:5px solid #666;display:flex;justify-content:space-between;gap:24px;align-items:center;margin-bottom:14px}.hero.ok{border-left-color:#71956a}.hero.warn{border-left-color:#c3994f}.hero.danger{border-left-color:#c95c54}.hero h2{font-size:32px;margin:4px 0}.hero strong{font-size:42px}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:14px}.card{padding:16px}.card span{display:block;font-size:11px;color:#918b7f}.card strong{display:block;font-size:22px;margin-top:5px}.panel{padding:18px;margin-bottom:14px}.panel h2{font-size:15px;margin:0 0 12px}.two{display:grid;grid-template-columns:1fr 1fr;gap:14px}.list{margin:0;padding-left:20px;color:#b9ad95;font-size:13px}.links{display:flex;gap:14px;flex-wrap:wrap;font-size:12px}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}.two{grid-template-columns:1fr}.top,.hero{align-items:flex-start;flex-direction:column}.meta{text-align:left}}@media(max-width:520px){.grid{grid-template-columns:1fr}}
</style></head><body><main><header class="top"><div><div class="eyebrow">TEHKNÉ SOLUTIONS · OPERATIONAL CONTROL</div><h1>Executive Health & Readiness</h1></div><div class="meta">storage: ${esc(meta.mode)} · release: ${esc(meta.release)}<br>gerado ${esc(health.generatedAt)}</div></header><section class="hero ${statusClass}"><div><div class="eyebrow">ESTADO OPERACIONAL</div><h2>${esc(label(health.status))}</h2><p>readiness: ${health.ready ? "liberado" : "não liberado"}</p></div><div><span class="eyebrow">HEALTH SCORE</span><strong>${health.score}</strong></div></section><section class="grid"><div class="card"><span>Quality Gate</span><strong>${esc(health.quality.status)}</strong></div><div class="card"><span>Recovery</span><strong>${esc(health.recovery.decision)}</strong></div><div class="card"><span>Incidentes ativos</span><strong>${health.incidents.active}</strong></div><div class="card"><span>Última promoção</span><strong>${esc(health.release.health)}</strong></div><div class="card"><span>Sentinela</span><strong>${esc(health.release.sentinelStatus)}</strong></div></section><section class="two"><div class="panel"><h2>Blockers</h2><ul class="list">${blockers}</ul></div><div class="panel"><h2>Warnings</h2><ul class="list">${warnings}</ul></div></section><section class="panel"><h2>Evidence</h2><div class="grid"><div class="card"><span>Quality SHA</span><strong>${esc(health.quality.candidateSha?.slice(0,12) ?? "—")}</strong></div><div class="card"><span>Release SHA</span><strong>${esc(health.release.candidateSha?.slice(0,12) ?? "—")}</strong></div><div class="card"><span>Regression budget</span><strong>${esc(health.quality.regressionBudget ?? "—")}</strong></div><div class="card"><span>Telemetry events</span><strong>${health.telemetry.events}</strong></div><div class="card"><span>Resolved incidents</span><strong>${health.incidents.resolved}</strong></div></div></section><section class="panel"><div class="links"><a href="/control">Control Center</a><a href="/promotions">Promotion Ledger</a><a href="/incidents">Incident Lifecycle</a><a href="/api/executive-health">Executive Health JSON</a><a href="/api/recovery">Recovery JSON</a></div></section></main></body></html>`;
}
