import type { ControlCenterSnapshot } from "@hnk/telemetry-control-core";
import { deriveIncidentLifecycles, type IncidentLifecycle, type IncidentLifecycleState } from "./incident-lifecycle.js";

function esc(value: unknown): string { return String(value ?? "").replace(/[&<>\"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[char] ?? char)); }
function labelState(state: IncidentLifecycle["state"]): string { return state === "new" ? "Novo" : state === "recurrent" ? "Reincidente" : "Regressão conhecida"; }
function lifecycleLabel(state: IncidentLifecycleState): string { return ({ open: "Aberto", investigating: "Investigando", mitigated: "Mitigado", resolved: "Resolvido" })[state]; }
function formatDuration(ms?: number): string { if (ms === undefined) return "—"; const minutes = Math.round(ms / 60_000); if (minutes < 60) return `${minutes}m`; const hours = Math.floor(minutes / 60); return `${hours}h ${minutes % 60}m`; }
function priority(incident: IncidentLifecycle): number { const severity = incident.severity === "fatal" ? 100 : 50; const lifecycle = incident.lifecycleState === "open" ? 40 : incident.lifecycleState === "investigating" ? 30 : incident.lifecycleState === "mitigated" ? 15 : 0; const recurrence = incident.state === "recurrent" ? 30 : incident.state === "known_regression" ? 20 : 10; return severity + lifecycle + recurrence + Math.min(incident.occurrences, 20); }

export function renderIncidentDashboard(snapshot: ControlCenterSnapshot, meta: { readonly mode: string; readonly release: string }): string {
  const incidents = [...deriveIncidentLifecycles(snapshot.recentEvents, snapshot.generatedAt)].sort((a, b) => priority(b) - priority(a) || b.lastSeenAt.localeCompare(a.lastSeenAt));
  const active = incidents.filter((item) => item.lifecycleState !== "resolved");
  const resolved = incidents.filter((item) => item.lifecycleState === "resolved");
  const resolvedWithMttr = resolved.filter((item) => item.mttrMs !== undefined);
  const avgMttr = resolvedWithMttr.length ? Math.round(resolvedWithMttr.reduce((sum, item) => sum + (item.mttrMs ?? 0), 0) / resolvedWithMttr.length) : undefined;
  const totals = { all: incidents.length, active: active.length, investigating: incidents.filter((item) => item.lifecycleState === "investigating").length, resolved: resolved.length };
  const domains = new Map<string, number>(); for (const incident of active) domains.set(incident.domain, (domains.get(incident.domain) ?? 0) + 1);
  const rows = incidents.map((incident) => `<tr>
    <td>${esc(incident.lastSeenAt.slice(5, 16).replace("T", " "))}</td>
    <td><span class="badge ${incident.lifecycleState === "resolved" ? "ok" : incident.severity === "fatal" ? "danger" : "warn"}">${esc(lifecycleLabel(incident.lifecycleState))}</span><br><small>${esc(labelState(incident.state))}</small></td>
    <td>${esc(incident.domain)}</td><td><code>${esc(incident.fingerprint)}</code></td><td>${incident.occurrences}</td>
    <td>${formatDuration(incident.openDurationMs)}</td><td>${formatDuration(incident.mttaMs)}</td><td>${formatDuration(incident.mttrMs)}</td>
    <td>${incident.reopenCount}</td><td>${incident.affectedBuildShas.map((sha) => `<code>${esc(sha.slice(0, 8))}</code>`).join(" ") || "—"}</td>
    <td>${incident.resolvedBuildSha ? `<code>${esc(incident.resolvedBuildSha.slice(0, 8))}</code>` : "—"}</td>
    <td class="failure">${esc(incident.failures.join(" · ") || "none")}</td><td>${esc(incident.recommendedAction)}</td>
  </tr>`).join("");
  const domainMetrics = [...domains.entries()].sort((a, b) => b[1] - a[1]).map(([domain, count]) => `<div class="metric"><span>${esc(domain)}</span><strong>${count}</strong></div>`).join("") || `<div class="empty">Nenhum domínio com incidente ativo.</div>`;
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="30"><title>HENUVOKODAN — Incident Lifecycle</title><style>
  :root{font-family:Inter,system-ui,sans-serif;color:#e8e4da;background:#10110f}*{box-sizing:border-box}body{margin:0;background:#10110f}main{width:min(1600px,calc(100% - 32px));margin:auto;padding:28px 0 60px}a{color:#d5c397;text-decoration:none}.top{display:flex;justify-content:space-between;gap:20px;align-items:end;margin-bottom:20px}.eyebrow{letter-spacing:.18em;font-size:11px;color:#aaa28f}h1{font-size:28px;margin:4px 0 0}.meta{font-size:12px;color:#8d887c;text-align:right}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:14px}.card,.panel{border:1px solid #34362f;background:#171915;border-radius:8px}.card{padding:16px}.card span,.metric span{display:block;color:#918b7f;font-size:11px}.card strong,.metric strong{display:block;font-size:25px;margin-top:5px}.panel{padding:18px;margin-bottom:14px}.panel h2{font-size:15px;margin:0 0 14px;color:#d4ccb9}.metrics{display:grid;grid-template-columns:repeat(6,1fr);gap:9px}.metric{padding:12px;border:1px solid #30332c}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px;min-width:1700px}th,td{text-align:left;padding:9px;border-bottom:1px solid #2b2d28;vertical-align:top}th{color:#8f897d;font-weight:500}.badge{display:inline-block;border:1px solid #444;border-radius:999px;padding:3px 7px;white-space:nowrap}.badge.warn{border-color:#c3994f}.badge.danger{border-color:#c95c54}.badge.ok{border-color:#6f9f71}.failure{max-width:320px;color:#b9ad95}.empty,small{color:#888276;font-size:11px}code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;color:#c8bda4}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}.metrics{grid-template-columns:repeat(2,1fr)}.top{align-items:flex-start;flex-direction:column}.meta{text-align:left}}@media(max-width:520px){.grid,.metrics{grid-template-columns:1fr}}
  </style></head><body><main><header class="top"><div><div class="eyebrow">TEHKNÉ SOLUTIONS · INCIDENT LIFECYCLE</div><h1>Incident Lifecycle</h1></div><div class="meta"><a href="/control">← Control Center</a> · <a href="/promotions">Promotion Ledger</a><br>storage: ${esc(meta.mode)} · release: ${esc(meta.release)}<br>gerado ${esc(snapshot.generatedAt)}</div></header><section class="grid"><div class="card"><span>Incidentes</span><strong>${totals.all}</strong></div><div class="card"><span>Ativos</span><strong>${totals.active}</strong></div><div class="card"><span>Investigando</span><strong>${totals.investigating}</strong></div><div class="card"><span>Resolvidos</span><strong>${totals.resolved}</strong></div><div class="card"><span>MTTR médio</span><strong>${formatDuration(avgMttr)}</strong></div></section><section class="panel"><h2>Incidentes ativos por domínio</h2><div class="metrics">${domainMetrics}</div></section><section class="panel"><h2>Lifecycle por fingerprint</h2>${rows ? `<div class="table-wrap"><table><thead><tr><th>Última ocorrência</th><th>Lifecycle / inteligência</th><th>Domínio</th><th>Fingerprint</th><th>Ocorrências</th><th>Tempo aberto</th><th>MTTA</th><th>MTTR</th><th>Reaberturas</th><th>SHAs afetados</th><th>SHA resolvido</th><th>Falhas</th><th>Ação recomendada</th></tr></thead><tbody>${rows}</tbody></table></div>` : `<div class="empty">Nenhum incidente pós-release detectado na janela.</div>`}</section></main></body></html>`;
}
